#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttpReports.Dashboard.Views
{
    using System;
    
    #line 3 "..\..\Views\HttpReports\EditMonitor.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class EditMonitor : HttpReports.Dashboard.Views.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




            
            #line 4 "..\..\Views\HttpReports\EditMonitor.cshtml"
  
    ViewData["Title"] = "EditMonitorRule";

    string Id = ViewData["Id"] as string;

    var nodes = ViewData["nodes"] as List<string>;

    var lang = ViewData["Language"] as HttpReports.Dashboard.Services.Localize;

    Layout = new HttpReports.Dashboard.Views.HttpReportsTemplate { Context = Context, ViewData = ViewData };



            
            #line default
            #line hidden
WriteLiteral(@"

<style type=""text/css"">

    .wizard-type1 .tab-pane {
        padding: 18px 6px;
    }

    .wizard-type1 ul.steps li.active a {
        border-left: 0;
        border-right: 0;
        border-bottom: 2px solid #67c2ef;
    }

    .wizard-type1 ul.steps li a {
        padding: 0;
        margin: 0 20px;
    }

    ");


WriteLiteral(@"@media screen and (min-width:1170px) {
        .title, .description, .email, .mobiles, .webhook {
            width: 75% !important;
        }
    }

    .tab-pane {
        margin-top: 12px;
        padding: 20px 15px;
        border-radius: 6px;
        border: 1px solid #ccc;
    }
</style>


<div class=""panel panel-default"">


    <div class=""panel-body  task_content"" style=""padding-left:30px;padding-right:30px;padding-top:30px;min-height:720px;padding-bottom:30px"">

        <ol class=""breadcrumb"">
            <li><a href=""/HttpReports/Monitor"">");


            
            #line 56 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                          Write(lang.Monitor_NavTitle);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><span href=\"#\">");


            
            #line 57 "..\..\Views\HttpReports\EditMonitor.cshtml"
                           Write(Id == "" || Id == "0" ? lang.Monitor_Add :lang.Monitor_Edit);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 57 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                         Write(lang.Task);

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n        </ol>\r\n\r\n        <h3 style=\"margin-bottom:20px;\">");


            
            #line 60 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                    Write(Id == "" || Id == "0" ? lang.Monitor_Add : lang.Monitor_Edit);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 60 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                                   Write(lang.Monitor_Task);

            
            #line default
            #line hidden
WriteLiteral(@"</h3>

        <div class=""row"">

            <div class=""panel panel-default"">
                <div class=""panel-body"" style=""padding:20px 35px"">

                    <div class=""row form-inline form"">

                        <div class=""row"" style=""margin-left:0;margin-right:0;margin-top:15px"">

                            <div class=""col-lg-9"">
                                <label style=""width:100px"" class=""form-label"">");


            
            #line 72 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                         Write(lang.Monitor_Title);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                <input type=\"text\" class=\"form-control " +
"title\" placeholder=\"");


            
            #line 73 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                      Write(lang.Monitor_Title_Placeholder);

            
            #line default
            #line hidden
WriteLiteral(@""">
                            </div>

                        </div>

                        <div class=""row"" style=""margin-left:0;margin-right:0;margin-top:15px"">

                            <div class=""col-lg-9"">
                                <label style=""width:100px"" class=""form-label"">");


            
            #line 81 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                         Write(lang.Monitor_Description);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                <input type=\"text\" class=\"form-control " +
"description\" placeholder=\"");


            
            #line 82 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                            Write(lang.Monitor_Desc_Placeholder);

            
            #line default
            #line hidden
WriteLiteral(@""">
                            </div>

                        </div>

                        <div class=""row"" style=""margin-left:0;margin-right:0;margin-top:15px;"">

                            <div class=""col-lg-9 node-row"">
                                <label style=""width:100px"" class=""form-label"">");


            
            #line 90 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                         Write(lang.Monitor_ServiceNode);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\r\n");


            
            #line 92 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                 foreach (var item in nodes)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <button onclick=\"check_node(this)\" style=\"wid" +
"th:120px;margin-right:10px;border-radius:4px;\" class=\"btn btn-info service-butto" +
"n\">");


            
            #line 94 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                                                                                               Write(item);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");


            
            #line 95 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral(@"
                            </div>

                        </div>

                        <div class=""row"" style=""margin-left:0;margin-right:0;margin-top:15px"">

                            <div class=""col-lg-9"">
                                <label style=""width:100px"" class=""form-label"">");


            
            #line 104 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                         Write(lang.Monitor_Email);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                <input type=\"text\" class=\"form-control " +
"email\" placeholder=\"");


            
            #line 105 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                      Write(lang.Monitor_Email_Placeholder);

            
            #line default
            #line hidden
WriteLiteral(@""">
                            </div>

                        </div>

                        <div class=""row"" style=""margin-left:0;margin-right:0;margin-top:15px"">

                            <div class=""col-lg-9"">
                                <label style=""width:100px"" class=""form-label"">");


            
            #line 113 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                         Write(lang.Monitor_PushUrl);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                <input type=\"text\" class=\"form-control " +
"webhook\" placeholder=\"");


            
            #line 114 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                        Write(lang.Monitor_Push_Placeholder);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\r\n                            </div>\r\n\r\n                        </div>\r\n\r\n\r\n " +
"                       ");



WriteLiteral(@"

                        <div class=""row"" style=""margin-left:0;margin-right:0;margin-top:15px;display:none"">

                            <div class=""col-lg-9"">
                                <label style=""width:100px"" class=""form-label"">手机号列表</label>
                                <input type=""text"" value="""" class=""form-control mobiles"" placeholder=""告警接收手机号，支持多手机号 10086,10010..."">
                            </div>

                        </div>

                        <div class=""row"" style=""margin-left:0;margin-right:0;margin-top:15px;"">

                            <div class=""col-lg-9"">
                                <label style=""width:100px"" class=""form-label"">");


            
            #line 135 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                         Write(lang.Monitor_Frequency);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                <select class=\"form-control interval\">\r" +
"\n                                    <option value=\"1\">");


            
            #line 137 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                 Write(lang.Monitor_Time1Min);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                                    <option value=\"3\">");


            
            #line 138 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                 Write(lang.Monitor_Time3Min);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                                    <option value=\"5\">");


            
            #line 139 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                 Write(lang.Monitor_Time5Min);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                                    <option value=\"10\">");


            
            #line 140 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                  Write(lang.Monitor_Time10Min);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                                    <option value=\"30\">");


            
            #line 141 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                  Write(lang.Monitor_Time30Min);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                                    <option value=\"60\" selected>");


            
            #line 142 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                           Write(lang.Monitor_Time1Hour);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                                    <option value=\"120\">");


            
            #line 143 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                   Write(lang.Monitor_Time2Hour);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                                    <option value=\"240\">");


            
            #line 144 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                   Write(lang.Monitor_Time4Hour);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                                    <option value=\"360\">");


            
            #line 145 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                   Write(lang.Monitor_Time6Hour);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                                    <option value=\"480\">");


            
            #line 146 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                   Write(lang.Monitor_Time8Hour);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                                    <option value=\"720\">");


            
            #line 147 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                   Write(lang.Monitor_Time12Hour);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                                    <option value=\"1440\">");


            
            #line 148 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                    Write(lang.Monitor_Time1Day);

            
            #line default
            #line hidden
WriteLiteral(@"</option>
                                </select>
                            </div>

                        </div>

                        <div class=""row"" style=""margin-left:0;margin-right:0;margin-top:15px"">

                            <div class=""col-lg-9"">
                                <label style=""width:100px"" class=""form-label"">");


            
            #line 157 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                         Write(lang.Monitor_State);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                <input type=\"checkbox\" checked class=\"c" +
"heckbox\" data-on-text=\"");


            
            #line 158 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                         Write(lang.Monitor_CheckBox_Open);

            
            #line default
            #line hidden
WriteLiteral("\" data-handle-width=\"30\" data-off-text=\"");


            
            #line 158 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                                                                                            Write(lang.Monitor_CheckBox_Close);

            
            #line default
            #line hidden
WriteLiteral(@""" data-size=""mini"" value="""" />
                            </div>

                        </div>


                    </div>

                    <div class=""clearfix"">
                    </div>


                    <div id=""wizard1"" class=""wizard-type1"" style=""margin-top:20px;"">

                        <div>

                            <ul class=""steps nav nav-pills"">
                                <li class=""active""><a href=""#tab11"" data-toggle=""tab""><span class=""badge badge-info""><i class=""fa fa-star""></i></span> ");


            
            #line 175 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                                                                                  Write(lang.Monitor_Type_Timeout);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                                <li class=\"\"><a href=\"#tab12\" data-tog" +
"gle=\"tab\"><span class=\"badge badge-info\"><i class=\"fa fa-credit-card\"></i></span" +
"> ");


            
            #line 176 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                                                                                   Write(lang.Monitor_Type_RequestError);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                                <li class=\"\"><a href=\"#tab13\" data-tog" +
"gle=\"tab\"><span class=\"badge badge-info\"><i class=\"fa fa-building\"></i></span> ");


            
            #line 177 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                                                                                Write(lang.Monitor_Type_IP);

            
            #line default
            #line hidden
WriteLiteral(" </a></li>\r\n                                <li class=\"\"><a href=\"#tab14\" data-to" +
"ggle=\"tab\"><span class=\"badge badge-info\"><i class=\"fa fa-rocket\"></i></span> ");


            
            #line 178 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                                                                              Write(lang.Monitor_Type_RequestCount);

            
            #line default
            #line hidden
WriteLiteral(@"</a></li>
                            </ul>


                        </div>

                        <div class=""tab-content"">

                            <div id=""tab11"" class=""tab-pane active"">

                                <div class=""row form-inline form"">

                                    <div class=""col-sm-12"">

                                        <div class=""col-lg-12"">

                                            <label class=""form-label"" style=""margin-right:10px"">");


            
            #line 194 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                           Write(lang.Monitor_State);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\r\n                                            <input data-id=\"0\" type=\"" +
"checkbox\" class=\"checkbox\" data-on-text=\"");


            
            #line 196 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                                         Write(lang.Monitor_CheckBox_Open);

            
            #line default
            #line hidden
WriteLiteral("\" data-handle-width=\"30\" data-off-text=\"");


            
            #line 196 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                                                                                                            Write(lang.Monitor_CheckBox_Close);

            
            #line default
            #line hidden
WriteLiteral(@""" data-size=""mini"" value="""" />

                                        </div>

                                    </div>


                                    <div class=""col-sm-12"" style=""margin-top:6px"">

                                        <div class=""col-sm-3"">
                                            <label class=""form-label"" style=""width:80px"">");


            
            #line 206 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                    Write(lang.Monitor_Timeout);

            
            #line default
            #line hidden
WriteLiteral(@"</label>
                                            <input type=""text"" class=""form-control RtTime"" placeholder="""">
                                        </div>

                                        <div class=""col-sm-3"" style=""padding:0"">
                                            <label class=""form-label"">");


            
            #line 211 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                 Write(lang.Monitor_Timeout_Percentage);

            
            #line default
            #line hidden
WriteLiteral(@"</label>
                                            <input type=""text"" value=""0.00%"" class=""form-control RtPercent"" placeholder=""0.01% 15% ... "">
                                        </div>

                                    </div>

                                    <div class=""col-sm-12"" style=""margin-top:20px;"">

                                        <div style=""margin-left:12px; margin-right:12px;margin-bottom:0"" class=""alert alert-info"" role=""alert"">

                                            <p><b>");


            
            #line 221 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                             Write(lang.Monitor_Type_Timeout);

            
            #line default
            #line hidden
WriteLiteral("</b>：");


            
            #line 221 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                            Write(lang.Monitor_Timeout_Description);

            
            #line default
            #line hidden
WriteLiteral(" </p>\r\n\r\n                                            <p>");


            
            #line 223 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                          Write(lang.Monitor_Timeout_Info);

            
            #line default
            #line hidden
WriteLiteral(@"</p>

                                        </div>

                                    </div>

                                </div>

                            </div>

                            <div class=""tab-pane"" id=""tab12"">

                                <div class=""row form-inline form"">

                                    <div class=""col-sm-12"">

                                        <div class=""col-lg-12"">

                                            <label class=""form-label"" style=""margin-right:10px"">");


            
            #line 241 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                           Write(lang.Monitor_State);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\r\n                                            <input type=\"checkbox\" cl" +
"ass=\"checkbox\" data-on-text=\"");


            
            #line 243 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                             Write(lang.Monitor_CheckBox_Open);

            
            #line default
            #line hidden
WriteLiteral("\" data-handle-width=\"30\" data-off-text=\"");


            
            #line 243 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                                                                                                Write(lang.Monitor_CheckBox_Close);

            
            #line default
            #line hidden
WriteLiteral(@""" data-size=""mini"" value="""" />

                                        </div>

                                    </div>

                                    <div class=""col-sm-12"" style=""margin-top:6px"">

                                        <div class=""col-sm-3"">
                                            <label class=""form-label"">");


            
            #line 252 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                 Write(lang.Monitor_HttpStatusCode);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                            <input type=\"text\" class=\"f" +
"orm-control HttpCodes\" placeholder=\"");


            
            #line 253 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                                      Write(lang.Monitor_HttpStatusCode_Desc);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                        </div>\r\n\r\n                           " +
"             <div class=\"col-sm-3\">\r\n                                           " +
" <label class=\"form-label\">");


            
            #line 257 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                 Write(lang.Monitor_Timeout_Percentage);

            
            #line default
            #line hidden
WriteLiteral(@"</label>
                                            <input type=""text"" value=""0.00%"" class=""form-control HttpPercent"" placeholder="" 0.01% 15% ... "">
                                        </div>

                                    </div>

                                    <div class=""col-sm-12"" style=""margin-top:20px;"">

                                        <div style=""margin-left:12px;margin-right:12px;margin-bottom:0"" class=""alert alert-info"" role=""alert"">

                                            <p><b>");


            
            #line 267 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                             Write(lang.Monitor_Type_RequestError);

            
            #line default
            #line hidden
WriteLiteral("</b>：");


            
            #line 267 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                 Write(lang.Monitor_Type_RequestError_Desc);

            
            #line default
            #line hidden
WriteLiteral(" </p>\r\n\r\n                                            <p>");


            
            #line 269 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                          Write(lang.Monitor_Type_RequestError_Info);

            
            #line default
            #line hidden
WriteLiteral(@"</p>

                                        </div>

                                    </div>

                                </div>

                            </div>

                            <div class=""tab-pane"" id=""tab13"">

                                <div class=""row form-inline form"">

                                    <div class=""col-sm-12"">

                                        <div class=""col-lg-12"">

                                            <label class=""form-label"" style=""margin-right:10px"">");


            
            #line 287 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                           Write(lang.Monitor_State);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\r\n                                            <input type=\"checkbox\" cl" +
"ass=\"checkbox\" data-on-text=\"");


            
            #line 289 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                             Write(lang.Monitor_CheckBox_Open);

            
            #line default
            #line hidden
WriteLiteral("\" data-handle-width=\"30\" data-off-text=\"");


            
            #line 289 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                                                                                                Write(lang.Monitor_CheckBox_Close);

            
            #line default
            #line hidden
WriteLiteral(@""" data-size=""mini"" value="""" />

                                        </div>

                                    </div>


                                    <div class=""col-sm-12"" style=""margin-top:6px"">

                                        <div class=""col-sm-3"">
                                            <label class=""form-label"">");


            
            #line 299 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                 Write(lang.Monitor_IPWhiteList);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                            <input type=\"text\" class=\"f" +
"orm-control IPWhiteList\" placeholder=\"");


            
            #line 300 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                                        Write(lang.Monitor_IPWhiteList_Placeholder);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                        </div>\r\n\r\n                           " +
"             <div class=\"col-sm-3\">\r\n                                           " +
" <label class=\"form-label\">");


            
            #line 304 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                 Write(lang.Monitor_Timeout_Percentage);

            
            #line default
            #line hidden
WriteLiteral(@"</label>
                                            <input value=""0.00%"" type=""text"" class=""form-control IPPercent"" placeholder=""0.01% 15% ... "">
                                        </div>

                                    </div>

                                    <div class=""col-sm-12"" style=""margin-top:20px;"">

                                        <div style=""margin-left:12px;margin-right:12px;margin-bottom:0"" class=""alert alert-info"" role=""alert"">

                                            <p><b>");


            
            #line 314 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                             Write(lang.Monitor_Type_IP);

            
            #line default
            #line hidden
WriteLiteral("</b>：");


            
            #line 314 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                       Write(lang.Monitor_IP_Desc);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n                                            <p> ");


            
            #line 316 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                           Write(lang.Monitor_IP_Info);

            
            #line default
            #line hidden
WriteLiteral(@" </p>

                                        </div>

                                    </div>

                                </div>


                            </div>

                            <div class=""tab-pane"" id=""tab14"">

                                <div class=""row form-inline form"">

                                    <div class=""col-sm-12"">

                                        <div class=""col-lg-12"">

                                            <label class=""form-label"" style=""margin-right:10px"">");


            
            #line 335 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                           Write(lang.Monitor_State);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\r\n                                            <input type=\"checkbox\" cl" +
"ass=\"checkbox\" data-on-text=\"");


            
            #line 337 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                             Write(lang.Monitor_CheckBox_Open);

            
            #line default
            #line hidden
WriteLiteral("\" data-handle-width=\"30\" data-off-text=\"");


            
            #line 337 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                                                                                                Write(lang.Monitor_CheckBox_Close);

            
            #line default
            #line hidden
WriteLiteral(@""" data-size=""mini"" value="""" />

                                        </div>

                                    </div>

                                    <div class=""col-sm-12"" style=""margin-top:6px"">

                                        <div class=""col-sm-3"">
                                            <label class=""form-label"">");


            
            #line 346 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                 Write(lang.Monitor_Max_Request);

            
            #line default
            #line hidden
WriteLiteral(@"</label>
                                            <input type=""text"" class=""form-control RequestCount"">
                                        </div>

                                    </div>

                                    <div class=""col-sm-12"" style=""margin-top:20px;"">

                                        <div style=""margin-left:12px;margin-right:12px;margin-bottom:0"" class=""alert alert-info"" role=""alert"">

                                            <p><b>");


            
            #line 356 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                             Write(lang.Monitor_Type_RequestCount);

            
            #line default
            #line hidden
WriteLiteral("</b>：");


            
            #line 356 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                 Write(lang.Monitor_Type_RequestCount_Desc);

            
            #line default
            #line hidden
WriteLiteral(" </p>\r\n\r\n                                            <p> ");


            
            #line 358 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                           Write(lang.Monitor_Type_RequestCount_Info);

            
            #line default
            #line hidden
WriteLiteral(@" </p>

                                        </div>

                                    </div>
                                </div>


                            </div>

                        </div>

                        <input type=""hidden"" class=""id"" value=""");


            
            #line 370 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                           Write(Id);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\r\n                        <div class=\"actions\" style=\"margin-top:15px;margin-" +
"bottom:8px;\">\r\n                            <button onclick=\"saveMonitorJob()\" ty" +
"pe=\"button\" class=\"btn btn-info button-previous\" style=\"width:80px\"> ");


            
            #line 373 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                                                                 Write(lang.Save);

            
            #line default
            #line hidden
WriteLiteral(" </button>\r\n\r\n                            <a href=\"/HttpReports/Monitor\" type=\"bu" +
"tton\" class=\"btn btn-info button-previous\" style=\"width:120px;margin-left:20px\">" +
" ");


            
            #line 375 "..\..\Views\HttpReports\EditMonitor.cshtml"
                                                                                                                                               Write(lang.Back);

            
            #line default
            #line hidden
WriteLiteral(" </a>\r\n\r\n                        </div>\r\n\r\n\r\n                    </div>\r\n\r\n      " +
"          </div>\r\n            </div>\r\n\r\n        </div>\r\n\r\n    </div>\r\n\r\n</div>\r\n" +
"\r\n<script src=\"/HttpReportsStaticFiles/Content/page/edit_monitor.js?ver=1.0.5\"><" +
"/script>\r\n\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
