#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttpReports.Dashboard.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class HttpReportsTemplate : HttpReports.Dashboard.Views.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



            
            #line 3 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
  
    var lang = ViewData["Language"] as HttpReports.Dashboard.Services.Localize;  


            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html lang=\"zh-cn\">\r\n<head>\r\n    <meta charset=\"utf-8\">\r\n    <" +
"meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n    <meta name=\"viewport\" " +
"content=\"width=device-width, initial-scale=1\">\r\n    <title>HttpReports</title>\r\n" +
"\r\n    <link href=\"/HttpReportsStaticFiles/Content/assets/css/bootstrap.min.css?v" +
"er=1.0.7\" rel=\"stylesheet\">\r\n    <link href=\"/HttpReportsStaticFiles/Content/ass" +
"ets/css/font-awesome.min.css?ver=1.0.7\" rel=\"stylesheet\">\r\n    <link href=\"/Http" +
"ReportsStaticFiles/Content/assets/css/jquery.mmenu.css?ver=1.0.7\" rel=\"styleshee" +
"t\" />\r\n    <link id=\"theme\" href=\"/HttpReportsStaticFiles/Content/assets/css/sty" +
"le.min.css?ver=1.0.7\" rel=\"stylesheet\">\r\n    <link href=\"/HttpReportsStaticFiles" +
"/Content/assets/css/add-ons.min.css?ver=1.0.7\" rel=\"stylesheet\">\r\n    <link href" +
"=\"/HttpReportsStaticFiles/Content/bootstrap/bootstrap_switch/_3._3._4/bootstrap-" +
"switch.css\" rel=\"stylesheet\" />\r\n\r\n\r\n    <link class=\"theme\" id=\"theme_light\" hr" +
"ef=\"/HttpReportsStaticFiles/Content/css/theme/light.css?ver=1.0.7\" rel=\"styleshe" +
"et\" />\r\n    <link class=\"theme\" id=\"theme_dark\" href=\"/HttpReportsStaticFiles/Co" +
"ntent/css/theme/dark.css?ver=1.0.7\" rel=\"stylesheet\" />\r\n    <link href=\"/HttpRe" +
"portsStaticFiles/Content/css/animate/_3._5._2/animate.min.css?ver=1.0.7\" rel=\"st" +
"ylesheet\" />\r\n\r\n\r\n    <script src=\"/HttpReportsStaticFiles/Content/assets/js/jqu" +
"ery-2.1.1.min.js?ver=1.0.7\"></script>\r\n    <script src=\"/HttpReportsStaticFiles/" +
"Content/js/jquery.cookie.js?ver=1.0.7\"></script>\r\n    <script src=\"/HttpReportsS" +
"taticFiles/Content/assets/js/jquery.mmenu.min.js?ver=1.0.7\"></script>\r\n    <scri" +
"pt src=\"/HttpReportsStaticFiles/Content/assets/js/core.min.js?ver=1.0.7\"></scrip" +
"t>\r\n    <script src=\"/HttpReportsStaticFiles/Content/bootstrap/bootstrap_table/_" +
"1._14._2/bootstrap-table.js?ver=1.0.7\"></script>\r\n\r\n    <script src=\"/HttpReport" +
"sStaticFiles/Content/assets/js/bootstrap-table-zh-CN.js?ver=1.0.7\"></script>\r\n  " +
"  <script src=\"/HttpReportsStaticFiles/Content/bootstrap/bootstrap_switch/_3._3." +
"_4/bootstrap-switch.js\"></script>\r\n\r\n\r\n    <script src=\"/HttpReportsStaticFiles/" +
"Content/assets/js/bootstrap.min.js?ver=1.0.7\"></script>\r\n\r\n    <link rel=\"styles" +
"heet\" href=\"/HttpReportsStaticFiles/Content/bootstrap/select/select.css?ver=1.0." +
"7\">\r\n    <script src=\"/HttpReportsStaticFiles/Content/bootstrap/select/select.js" +
"?ver=1.0.7\"></script>\r\n\r\n\r\n    <script src=\"/HttpReportsStaticFiles/Content/echa" +
"rts/_4._3._0/echarts.min.js?ver=1.0.7\"></script>\r\n    <script src=\"/HttpReportsS" +
"taticFiles/Content/echarts/_4._3._0/macarons.js?ver=1.0.7\"></script>\r\n    <scrip" +
"t src=\"/HttpReportsStaticFiles/Content/echarts/_4._3._0/dark.js?ver=1.0.7\"></scr" +
"ipt>\r\n\r\n    <link href=\"/HttpReportsStaticFiles/Content/busyload/app.css?ver=1.0" +
".7\" rel=\"stylesheet\" />\r\n    <script src=\"/HttpReportsStaticFiles/Content/busylo" +
"ad/app.js?ver=1.0.7\"></script>\r\n\r\n    <!-- CSS 引入 -->\r\n    <script src=\"/HttpRep" +
"ortsStaticFiles/Content/laydate/laydate.js?ver=1.0.7\"></script>\r\n\r\n    <script s" +
"rc=\"/HttpReportsStaticFiles/Content/assets/js/jquery.goup.js?ver=1.0.7\"></script" +
">\r\n\r\n    <link href=\"/HttpReportsStaticFiles/Content/alert/alert.css?ver=1.0.7\" " +
"rel=\"stylesheet\" />\r\n\r\n    <script src=\"/HttpReportsStaticFiles/Content/alert/al" +
"ert.js?ver=1.0.7\"></script>\r\n    <script src=\"/HttpReportsStaticFiles/Content/js" +
"/bootstrap-treeview.js?ver=1.0.7\"></script>\r\n\r\n    <script src=\"/HttpReportsStat" +
"icFiles/Content/js/mSlider.min.js\"></script>\r\n    <script src=\"/HttpReportsStati" +
"cFiles/Content/js/jquery.nicescroll.js\"></script>\r\n\r\n\r\n    <link href=\"/HttpRepo" +
"rtsStaticFiles/Content/message/message.css?ver=1.0.7\" rel=\"stylesheet\" />\r\n    <" +
"script src=\"/HttpReportsStaticFiles/Content/message/message.js?ver=1.0.7\"></scri" +
"pt>\r\n\r\n    <script>  var langFormat = \'");


            
            #line 68 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                            Write(lang.LanguageFormat);

            
            #line default
            #line hidden
WriteLiteral("\';   </script>\r\n\r\n    <script src=\"/HttpReportsStaticFiles/Content/common/basic.j" +
"s?ver=1.0.7\"></script>\r\n    <link href=\"/HttpReportsStaticFiles/Content/common/b" +
"asic.css?ver=1.0.7\" rel=\"stylesheet\" />\r\n\r\n\r\n    <script src=\"/HttpReportsStatic" +
"Files/Content/page/main.js?ver=1.0.7\"></script> \r\n\r\n    <link rel=\"icon\" href=\"/" +
"HttpReportsStaticFiles/Content/assets/img/img.ico?ver=1.0.7\" type=\"image/x-icon\"" +
" />\r\n\r\n</head>\r\n\r\n<body> \r\n\r\n\r\n    <!-- start: Header -->\r\n    <div class=\"navba" +
"r\" role=\"navigation\">\r\n\r\n        <div class=\"container-fluid\">\r\n\r\n            <u" +
"l class=\"nav navbar-nav navbar-actions navbar-left\">\r\n                <li class=" +
"\"visible-md visible-lg\"><a href=\"#\" style=\"padding:0 10px;\" id=\"main-menu-toggle" +
"\"><i class=\"fa fa-th-large\"></i></a></li>\r\n                <li class=\"visible-xs" +
" visible-sm\"><a href=\"#\" id=\"sidebar-menu\"><i class=\"fa fa-navicon\"></i></a></li" +
">\r\n            </ul>\r\n\r\n            <ul class=\"nav navbar-nav navbar-right\"> \r\n\r" +
"\n                <li class=\"dropdown\" style=\"display:none\">\r\n                   " +
" <a  style=\"margin-top:2px\"  href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropd" +
"own\"><i class=\"fa fa-refresh\"></i></a>\r\n                    <ul class=\"dropdown-" +
"menu update-menu\" role=\"menu\">\r\n                        <li>\r\n                  " +
"          <a data-stopPropagation=\"true\" class=\"auto_refresh_menu\">\r\n           " +
"                     <select class=\"selectpicker service\"  data-style=\"btn-prima" +
"ry\" data-width=\"220px\" style=\"margin-right:20px\">\r\n                             " +
"       <option>ALL</option>\r\n                                </select>\r\n        " +
"                    </a>\r\n                        </li> \r\n                    </" +
"ul>\r\n                </li> \r\n                \r\n\r\n\r\n                <li class=\"dr" +
"opdown\">\r\n                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"d" +
"ropdown\"><i style=\"margin-top:24px;\" class=\"fa fa-language\"></i></a>\r\n          " +
"          <ul class=\"dropdown-menu update-menu\" role=\"menu\">\r\n                  " +
"      <li>\r\n                            <a data-key=\"en-us\" onclick=\"ChangeLangu" +
"age(this)\"> English </a>\r\n                        </li>\r\n                       " +
" <li>\r\n                            <a data-key=\"zh-cn\" onclick=\"ChangeLanguage(t" +
"his)\"> 中文</a>\r\n                        </li>\r\n                    </ul>\r\n       " +
"         </li>\r\n\r\n                <li class=\"dropdown\">\r\n                    <a " +
"href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"fa fa-dashboar" +
"d\"></i></a>\r\n                    <ul class=\"dropdown-menu update-menu\" role=\"men" +
"u\">\r\n                        <li>\r\n                            <a data-key=\"ligh" +
"t\" onclick=\"ChangeTheme(this)\"><i class=\"fa fa-sun-o\"></i> ");


            
            #line 126 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                                                                   Write(lang.Template_Light);

            
            #line default
            #line hidden
WriteLiteral(" </a>\r\n                        </li>\r\n                        <li>\r\n             " +
"               <a data-key=\"dark\" onclick=\"ChangeTheme(this)\"><i class=\"fa fa-mo" +
"on-o\"></i> ");


            
            #line 129 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                                                                   Write(lang.Template_Dark);

            
            #line default
            #line hidden
WriteLiteral(@" </a>
                        </li>
                    </ul>
                </li>

                <li class=""dropdown"" style=""margin-right:20px"">
                    <a href=""#"" class=""dropdown-toggle"" data-toggle=""dropdown""><i class=""fa fa-user""></i></a>
                    <ul class=""dropdown-menu update-menu"" role=""menu"">
                        <li>
                            <a>admin</a>
                        </li>
                        <li>
                            <a onclick=""show_password_modal()""> ");


            
            #line 141 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                           Write(lang.Template_EditAccount);

            
            #line default
            #line hidden
WriteLiteral(" </a>\r\n                        </li>\r\n                        <li>\r\n             " +
"               <a href=\"/HttpReports/UserLogOut\"> ");


            
            #line 144 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                          Write(lang.Template_Logout);

            
            #line default
            #line hidden
WriteLiteral(@" </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
    <!-- end: Header -->

    <div class=""container-fluid content"">

        <div class=""row"">

            <!-- start: Main Menu -->
            <div class=""sidebar"">

                <div class=""sidebar-collapse"">
                    <div class=""sidebar-header t-center"">
                        <a id=""logo_title"" href=""/HttpReports"" class=""logo_title"" style=""line-height: 44px; margin-left: 48px;  font-size: 18px;text-align:center;float:left;font-weight:bold;color:#FFF;text-decoration: none"">HttpReports</a>
                    </div>
                    <div class=""sidebar-menu"">

                        <ul class=""nav nav-sidebar"">

                            <li class=""meun1""><a href=""/HttpReports/Index""><i class=""fa fa-laptop""></i><span class=""text"">");


            
            #line 168 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                                                                                     Write(lang.Menu_BasicData);

            
            #line default
            #line hidden
WriteLiteral("</span></a></li>\r\n\r\n                            <li class=\"meun1\"><a href=\"/HttpR" +
"eports/Trend\"><i class=\"fa fa-bar-chart-o\"></i><span class=\"text\">");


            
            #line 170 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                                                                                          Write(lang.Menu_TrendData);

            
            #line default
            #line hidden
WriteLiteral("</span></a></li>\r\n\r\n                            <li class=\"\"><a href=\"/HttpReport" +
"s/Detail\"><i class=\"fa fa-bars\"></i><span class=\"text\">");


            
            #line 172 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                                                                               Write(lang.Menu_RequestList);

            
            #line default
            #line hidden
WriteLiteral("</span></a></li>\r\n\r\n                            <li class=\"\"><a href=\"/HttpReport" +
"s/Monitor\"><i class=\"fa fa-rocket\"></i><span class=\"text\">");


            
            #line 174 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                                                                                  Write(lang.Menu_Monitor);

            
            #line default
            #line hidden
WriteLiteral("</span></a></li>\r\n\r\n                            <li class=\"\"><a href=\"/HttpReport" +
"s/Performance\"><i class=\"fa fa-flask\"></i><span class=\"text\">");


            
            #line 176 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                                                                                     Write(lang.Performance);

            
            #line default
            #line hidden
WriteLiteral(@"</span></a></li>

                        </ul>
                    </div>
                </div>
                <div class=""sidebar-footer"">
                </div>
            </div>
            <!-- end: Main Menu -->
            <!-- start: Content -->
            <div class=""main"" style=""width:98%;margin:20px auto"">

                ");


            
            #line 188 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral(@"
            </div>

            <!-- end: Content -->
            <br>

            <p class=""footer-copyright"" style=""text-align:center;font-size:14px"">HttpReports - SpringLee</p>
            <br><br>
        </div><!--/container-->
    </div>


    <div class=""modal fade userModal"" tabindex=""-1"" role=""dialog"">
        <div class=""modal-dialog modal-sm"" role=""document"">
            <div class=""modal-content"">
                <div class=""modal-header"">
                    <button type=""button"" class=""close"" data-dismiss=""modal"" aria-label=""Close""><span aria-hidden=""true"">&times;</span></button>
                    <span class=""modal-title"">");


            
            #line 205 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                         Write(lang.Template_EditAccount);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </div>\r\n                <div class=\"modal-body\">\r\n      " +
"              <div class=\"form-group\">\r\n                        <label>");


            
            #line 209 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                          Write(lang.Login_UserName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <input autocomplete=\"new-password\" type=\"text\" " +
"class=\"form-control update_username\">\r\n                    </div>\r\n             " +
"       <div class=\"form-group\">\r\n                        <label>");


            
            #line 213 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                          Write(lang.Index_OldPwd);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <input autocomplete=\"new-password\" type=\"passwo" +
"rd\" class=\"form-control update_oldpwd\">\r\n                    </div>\r\n           " +
"         <div class=\"form-group\">\r\n                        <label>");


            
            #line 217 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                          Write(lang.Index_NewPwd);

            
            #line default
            #line hidden
WriteLiteral(@"</label>
                        <input autocomplete=""new-password"" type=""password"" class=""form-control update_newpwd"">
                    </div>
                    <button style=""width:100%"" type=""submit"" onclick=""update_password()"" class=""btn btn-info"">");


            
            #line 220 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                                                                         Write(lang.Index_UserSave);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>" +
"\r\n\r\n\r\n    <div class=\"clearfix\"></div>  \r\n\r\n</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
