#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttpReports.Dashboard.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class HttpReportsTemplate : HttpReports.Dashboard.Views.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



            
            #line 3 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
  
    var lang = ViewData["Language"] as HttpReports.Dashboard.Services.Localize;  


            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html lang=\"zh-cn\">\r\n<head>\r\n    <meta charset=\"utf-8\">\r\n    <" +
"meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n    <meta name=\"viewport\" " +
"content=\"width=device-width, initial-scale=1\">\r\n    <title>HttpReports</title>\r\n" +
"\r\n    <link href=\"/HttpReportsStaticFiles/Content/assets/css/bootstrap.min.css\" " +
"rel=\"stylesheet\">\r\n    <link href=\"/HttpReportsStaticFiles/Content/assets/css/fo" +
"nt-awesome.min.css\" rel=\"stylesheet\">\r\n    <link href=\"/HttpReportsStaticFiles/C" +
"ontent/assets/css/jquery.mmenu.css\" rel=\"stylesheet\" />\r\n    <link id=\"theme\" hr" +
"ef=\"/HttpReportsStaticFiles/Content/assets/css/style.min.css?ver=1.0.5\" rel=\"sty" +
"lesheet\">\r\n    <link href=\"/HttpReportsStaticFiles/Content/assets/css/add-ons.mi" +
"n.css?ver=1.0.5\" rel=\"stylesheet\">\r\n    <link href=\"/HttpReportsStaticFiles/Cont" +
"ent/bootstrap/bootstrap_switch/_3._3._4/bootstrap-switch.css\" rel=\"stylesheet\" /" +
">\r\n\r\n\r\n    <link class=\"theme\" id=\"theme_light\" href=\"/HttpReportsStaticFiles/Co" +
"ntent/css/theme/light.css?ver=1.0.5\" rel=\"stylesheet\" />\r\n    <link class=\"theme" +
"\" id=\"theme_dark\" href=\"/HttpReportsStaticFiles/Content/css/theme/dark.css?ver=1" +
".0.5\" rel=\"stylesheet\" />\r\n    <link href=\"/HttpReportsStaticFiles/Content/css/a" +
"nimate/_3._5._2/animate.min.css\" rel=\"stylesheet\" />\r\n\r\n\r\n    <script src=\"/Http" +
"ReportsStaticFiles/Content/assets/js/jquery-2.1.1.min.js\"></script>\r\n    <script" +
" src=\"/HttpReportsStaticFiles/Content/js/jquery.cookie.js\"></script>\r\n    <scrip" +
"t src=\"/HttpReportsStaticFiles/Content/assets/js/jquery.mmenu.min.js\"></script>\r" +
"\n    <script src=\"/HttpReportsStaticFiles/Content/assets/js/core.min.js?ver=1.0." +
"5\"></script>\r\n    <script src=\"/HttpReportsStaticFiles/Content/bootstrap/bootstr" +
"ap_table/_1._14._2/bootstrap-table.js\"></script>\r\n\r\n    <script src=\"/HttpReport" +
"sStaticFiles/Content/assets/js/bootstrap-table-zh-CN.js\"></script>\r\n    <script " +
"src=\"/HttpReportsStaticFiles/Content/bootstrap/bootstrap_switch/_3._3._4/bootstr" +
"ap-switch.js\"></script>\r\n\r\n\r\n    <script src=\"/HttpReportsStaticFiles/Content/as" +
"sets/js/bootstrap.min.js\"></script>\r\n\r\n    <link rel=\"stylesheet\" href=\"/HttpRep" +
"ortsStaticFiles/Content/bootstrap/select/select.css\"> \r\n    <script src=\"/HttpRe" +
"portsStaticFiles/Content/bootstrap/select/select.js\"></script>\r\n\r\n\r\n    <script " +
"src=\"/HttpReportsStaticFiles/Content/echarts/_4._3._0/echarts.min.js\"></script>\r" +
"\n    <script src=\"/HttpReportsStaticFiles/Content/echarts/_4._3._0/macarons.js\">" +
"</script>\r\n    <script src=\"/HttpReportsStaticFiles/Content/echarts/_4._3._0/dar" +
"k.js\"></script>\r\n\r\n    <link href=\"/HttpReportsStaticFiles/Content/busyload/app." +
"css?ver=1.0.5\" rel=\"stylesheet\" />\r\n    <script src=\"/HttpReportsStaticFiles/Con" +
"tent/busyload/app.js?ver=1.0.5\"></script>\r\n\r\n    <!-- CSS 引入 -->\r\n    <script sr" +
"c=\"/HttpReportsStaticFiles/Content/laydate/laydate.js\"></script>\r\n\r\n    <script " +
"src=\"/HttpReportsStaticFiles/Content/assets/js/jquery.goup.js\"></script>\r\n\r\n    " +
"<link href=\"/HttpReportsStaticFiles/Content/alert/alert.css?ver=1.0.5\" rel=\"styl" +
"esheet\" />\r\n\r\n    <script src=\"/HttpReportsStaticFiles/Content/alert/alert.js?ve" +
"r=1.0.5\"></script>\r\n    <script src=\"/HttpReportsStaticFiles/Content/js/bootstra" +
"p-treeview.js?ver=1.0.5\"></script>\r\n\r\n\r\n    <link href=\"/HttpReportsStaticFiles/" +
"Content/message/message.css\" rel=\"stylesheet\" />\r\n    <script src=\"/HttpReportsS" +
"taticFiles/Content/message/message.js\"></script> >\r\n\r\n    <script>  var langForm" +
"at = \'");


            
            #line 65 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                            Write(lang.LanguageFormat);

            
            #line default
            #line hidden
WriteLiteral("\';   </script>\r\n\r\n    <script src=\"/HttpReportsStaticFiles/Content/common/basic.j" +
"s?ver=1.0.5\"></script>\r\n    <link href=\"/HttpReportsStaticFiles/Content/common/b" +
"asic.css?ver=1.0.5\" rel=\"stylesheet\" />\r\n\r\n\r\n    <script src=\"/HttpReportsStatic" +
"Files/Content/page/main.js?ver=1.0.5\"></script>\r\n\r\n\r\n    <link rel=\"icon\" href=\"" +
"/HttpReportsStaticFiles/Content/assets/img/img.ico\" type=\"image/x-icon\" />\r\n\r\n</" +
"head>\r\n\r\n<body> \r\n\r\n\r\n    <!-- start: Header -->\r\n    <div class=\"navbar\" role=\"" +
"navigation\">\r\n\r\n        <div class=\"container-fluid\">\r\n\r\n            <ul class=\"" +
"nav navbar-nav navbar-actions navbar-left\">\r\n                <li class=\"visible-" +
"md visible-lg\"><a href=\"#\" style=\"padding:0 10px;\" id=\"main-menu-toggle\"><i clas" +
"s=\"fa fa-th-large\"></i></a></li>\r\n                <li class=\"visible-xs visible-" +
"sm\"><a href=\"#\" id=\"sidebar-menu\"><i class=\"fa fa-navicon\"></i></a></li>\r\n      " +
"      </ul>\r\n\r\n            <ul class=\"nav navbar-nav navbar-right\">\r\n\r\n         " +
"       <li class=\"dropdown\">\r\n                    <a href=\"#\" class=\"dropdown-to" +
"ggle\" data-toggle=\"dropdown\"><i style=\"margin-top:24px;\" class=\"fa fa-language\">" +
"</i></a>\r\n                    <ul class=\"dropdown-menu update-menu\" role=\"menu\">" +
"\r\n                        <li>\r\n                            <a data-key=\"en-us\" " +
"onclick=\"ChangeLanguage(this)\"> English </a>\r\n                        </li>\r\n   " +
"                     <li>\r\n                            <a data-key=\"zh-cn\" oncli" +
"ck=\"ChangeLanguage(this)\"> 中文</a>\r\n                        </li>\r\n              " +
"      </ul>\r\n                </li>\r\n\r\n                <li class=\"dropdown\">\r\n   " +
"                 <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i c" +
"lass=\"fa fa-dashboard\"></i></a>\r\n                    <ul class=\"dropdown-menu up" +
"date-menu\" role=\"menu\">\r\n                        <li>\r\n                         " +
"   <a data-key=\"light\" onclick=\"ChangeTheme(this)\"><i class=\"fa fa-sun-o\"></i> ");


            
            #line 109 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                                                                   Write(lang.Template_Light);

            
            #line default
            #line hidden
WriteLiteral(" </a>\r\n                        </li>\r\n                        <li>\r\n             " +
"               <a data-key=\"dark\" onclick=\"ChangeTheme(this)\"><i class=\"fa fa-mo" +
"on-o\"></i> ");


            
            #line 112 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                                                                   Write(lang.Template_Dark);

            
            #line default
            #line hidden
WriteLiteral(@" </a>
                        </li>
                    </ul>
                </li>

                <li class=""dropdown"" style=""margin-right:20px"">
                    <a href=""#"" class=""dropdown-toggle"" data-toggle=""dropdown""><i class=""fa fa-user""></i></a>
                    <ul class=""dropdown-menu update-menu"" role=""menu"">
                        <li>
                            <a>admin</a>
                        </li>
                        <li>
                            <a onclick=""show_password_modal()""> ");


            
            #line 124 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                           Write(lang.Template_EditAccount);

            
            #line default
            #line hidden
WriteLiteral(" </a>\r\n                        </li>\r\n                        <li>\r\n             " +
"               <a href=\"/HttpReports/UserLogOut\"> ");


            
            #line 127 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                          Write(lang.Template_Logout);

            
            #line default
            #line hidden
WriteLiteral(@" </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
    <!-- end: Header -->

    <div class=""container-fluid content"">

        <div class=""row"">

            <!-- start: Main Menu -->
            <div class=""sidebar"">

                <div class=""sidebar-collapse"">
                    <div class=""sidebar-header t-center"">
                        <a id=""logo_title"" href=""/HttpReports"" class=""logo_title animated pulse infinite slow"" style=""line-height: 44px; margin-left: 48px;  font-size: 18px;text-align:center;float:left;font-weight:bold;color:#FFF;text-decoration: none"">HttpReports</a>
                    </div>
                    <div class=""sidebar-menu"">

                        <ul class=""nav nav-sidebar"">

                            <li data-title=""HomePage1"" class=""meun1""><a href=""/HttpReports/Index""><i class=""fa fa-laptop""></i><span class=""text"">");


            
            #line 151 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                                                                                                            Write(lang.Menu_BasicData);

            
            #line default
            #line hidden
WriteLiteral("</span></a></li>\r\n\r\n                            <li data-title=\"HomePage1\" class=" +
"\"meun1\"><a href=\"/HttpReports/Trend\"><i class=\"fa fa-bar-chart-o\"></i><span clas" +
"s=\"text\">");


            
            #line 153 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                                                                                                                 Write(lang.Menu_TrendData);

            
            #line default
            #line hidden
WriteLiteral("</span></a></li>\r\n\r\n                            <li data-title=\"HomePage1\" class=" +
"\"\"><a href=\"/HttpReports/Detail\"><i class=\"fa fa-bars\"></i><span class=\"text\">");


            
            #line 155 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                                                                                                      Write(lang.Menu_RequestList);

            
            #line default
            #line hidden
WriteLiteral("</span></a></li>\r\n\r\n                            <li data-title=\"HomePage1\" class=" +
"\"\"><a href=\"/HttpReports/Monitor\"><i class=\"fa fa-rocket\"></i><span class=\"text\"" +
">");


            
            #line 157 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                                                                                                         Write(lang.Menu_Monitor);

            
            #line default
            #line hidden
WriteLiteral(@"</span></a></li>
                        </ul>
                    </div>
                </div>
                <div class=""sidebar-footer"">
                </div>
            </div>
            <!-- end: Main Menu -->
            <!-- start: Content -->
            <div class=""main"" style=""width:98%;margin:20px auto"">

                ");


            
            #line 168 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral(@"
            </div>

            <!-- end: Content -->
            <br>

            <p class=""footer-copyright"" style=""text-align:center;font-size:14px"">HttpReports - SpringLee</p>
            <br><br>
        </div><!--/container-->
    </div>


    <div class=""modal fade userModal"" tabindex=""-1"" role=""dialog"">
        <div class=""modal-dialog modal-sm"" role=""document"">
            <div class=""modal-content"">
                <div class=""modal-header"">
                    <button type=""button"" class=""close"" data-dismiss=""modal"" aria-label=""Close""><span aria-hidden=""true"">&times;</span></button>
                    <span class=""modal-title"">");


            
            #line 185 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                         Write(lang.Template_EditAccount);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </div>\r\n                <div class=\"modal-body\">\r\n      " +
"              <div class=\"form-group\">\r\n                        <label>");


            
            #line 189 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                          Write(lang.Login_UserName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <input autocomplete=\"new-password\" type=\"text\" " +
"class=\"form-control update_username\">\r\n                    </div>\r\n             " +
"       <div class=\"form-group\">\r\n                        <label>");


            
            #line 193 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                          Write(lang.Index_OldPwd);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <input autocomplete=\"new-password\" type=\"passwo" +
"rd\" class=\"form-control update_oldpwd\">\r\n                    </div>\r\n           " +
"         <div class=\"form-group\">\r\n                        <label>");


            
            #line 197 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                          Write(lang.Index_NewPwd);

            
            #line default
            #line hidden
WriteLiteral(@"</label>
                        <input autocomplete=""new-password"" type=""password"" class=""form-control update_newpwd"">
                    </div>
                    <button style=""width:100%"" type=""submit"" onclick=""update_password()"" class=""btn btn-info"">");


            
            #line 200 "..\..\Views\HttpReports\HttpReportsTemplate.cshtml"
                                                                                                         Write(lang.Index_UserSave);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>" +
"\r\n\r\n\r\n    <div class=\"clearfix\"></div>\r\n\r\n\r\n</body>\r\n    </html>\r\n");


        }
    }
}
#pragma warning restore 1591
