#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttpReports.Dashboard.Views
{
    using System;
    
    #line 3 "..\..\Views\HttpReports\Monitor.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Monitor : HttpReports.Dashboard.Views.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




            
            #line 4 "..\..\Views\HttpReports\Monitor.cshtml"
  
    ViewData["Title"] = "MonitorRule";

    List<HttpReports.Monitor.IMonitorJob> list = ViewData["list"] as List<HttpReports.Monitor.IMonitorJob>;

    var lang = ViewData["Language"] as HttpReports.Dashboard.Services.Localize;

    Layout = new HttpReports.Dashboard.Views.HttpReportsTemplate { Context = Context, ViewData = ViewData };



            
            #line default
            #line hidden
WriteLiteral(@"

<style type=""text/css"">

    .table td, th {
        text-align: center;
        line-height: 24px !important;
    }
</style>

<div class=""panel panel-default"">

    <div class=""panel-body"" style=""padding-left:30px;padding-right:30px;padding-top:30px;padding-bottom:30px"">

        <div class=""row"">

            <div class=""panel panel-default"">
                <div class=""panel-body"" style=""padding-bottom:20px"">

                    <div class=""col-sm-12"" style=""margin-bottom:30px;padding:0"">

                        <div class=""col-sm-3"" style=""padding-left:0"">

                            <a style=""min-width:120px;"" href=""/HttpReports/EditMonitor"" class=""btn btn-primary btn-search"">");


            
            #line 37 "..\..\Views\HttpReports\Monitor.cshtml"
                                                                                                                      Write(lang.Monitor_Add);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\r\n                        </div>\r\n\r\n                    </div>\r\n\r\n         " +
"           <table class=\"table table-striped table-bordered\">\r\n                 " +
"       <thead>\r\n                            <tr>\r\n                              " +
"  <th>");


            
            #line 46 "..\..\Views\HttpReports\Monitor.cshtml"
                               Write(lang.Monitor_Title);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th>");


            
            #line 47 "..\..\Views\HttpReports\Monitor.cshtml"
                               Write(lang.Monitor_State);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th>");


            
            #line 48 "..\..\Views\HttpReports\Monitor.cshtml"
                               Write(lang.Monitor_Frequency);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th>");


            
            #line 49 "..\..\Views\HttpReports\Monitor.cshtml"
                               Write(lang.Monitor_Email);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th>");


            
            #line 50 "..\..\Views\HttpReports\Monitor.cshtml"
                               Write(lang.Monitor_ServiceNode);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th width=\"276\">");


            
            #line 51 "..\..\Views\HttpReports\Monitor.cshtml"
                                           Write(lang.Monitor_Operation);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            </tr>\r\n                        </thead>\r\n     " +
"                   <tbody>\r\n\r\n");


            
            #line 56 "..\..\Views\HttpReports\Monitor.cshtml"
                             foreach (var item in list)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <tr>\r\n                                    <td>");


            
            #line 59 "..\..\Views\HttpReports\Monitor.cshtml"
                                   Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td>\r\n\r\n");


            
            #line 62 "..\..\Views\HttpReports\Monitor.cshtml"
                                         if (item.Status == 1)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <span style=\"width: 60px;padding-left" +
":10px; padding-right:10px;margin-right: 8px;border-radius:0;\" class=\"label label" +
"-success\">");


            
            #line 64 "..\..\Views\HttpReports\Monitor.cshtml"
                                                                                                                                                                      Write(lang.Monitor_Runing);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 65 "..\..\Views\HttpReports\Monitor.cshtml"
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <span style=\"width: 60px;padding-left" +
":10px; padding-right:10px;margin-right: 8px;border-radius:0;\" class=\"label label" +
"-danger\">");


            
            #line 68 "..\..\Views\HttpReports\Monitor.cshtml"
                                                                                                                                                                     Write(lang.Monitor_Stoping);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 69 "..\..\Views\HttpReports\Monitor.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                    " +
"<td>");


            
            #line 72 "..\..\Views\HttpReports\Monitor.cshtml"
                                   Write(item.CronLike);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td>");


            
            #line 73 "..\..\Views\HttpReports\Monitor.cshtml"
                                   Write(item.Emails);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td>");


            
            #line 74 "..\..\Views\HttpReports\Monitor.cshtml"
                                   Write(item.Nodes);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\r\n                                    <td>\r\n\r\n                            " +
"            <a href=\"/HttpReports/EditMonitor?Id=");


            
            #line 78 "..\..\Views\HttpReports\Monitor.cshtml"
                                                                        Write(item.Id);

            
            #line default
            #line hidden
WriteLiteral("\" style=\"margin:4px\" type=\"button\" class=\"btn btn-info btn-xs\"><span class=\"glyph" +
"icon glyphicon-edit\"></span> ");


            
            #line 78 "..\..\Views\HttpReports\Monitor.cshtml"
                                                                                                                                                                                              Write(lang.Monitor_Edit);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\r\n");


            
            #line 80 "..\..\Views\HttpReports\Monitor.cshtml"
                                         if (item.Status == 1)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <button style=\"margin:4px\" type=\"butt" +
"on\" onclick=\"stopJob(\'");


            
            #line 82 "..\..\Views\HttpReports\Monitor.cshtml"
                                                                                                  Write(item.Id);

            
            #line default
            #line hidden
WriteLiteral("\')\" class=\"btn btn-primary btn-xs\"><span class=\"glyphicon glyphicon-off\"></span> " +
"");


            
            #line 82 "..\..\Views\HttpReports\Monitor.cshtml"
                                                                                                                                                                                           Write(lang.Monitor_Stop);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");


            
            #line 83 "..\..\Views\HttpReports\Monitor.cshtml"
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <button style=\"margin:4px\" type=\"butt" +
"on\" onclick=\"startJob(\'");


            
            #line 86 "..\..\Views\HttpReports\Monitor.cshtml"
                                                                                                   Write(item.Id);

            
            #line default
            #line hidden
WriteLiteral("\')\" class=\"btn btn-success btn-xs\"><span class=\"glyphicon glyphicon-play-circle\">" +
"</span> ");


            
            #line 86 "..\..\Views\HttpReports\Monitor.cshtml"
                                                                                                                                                                                                    Write(lang.Monitor_Start);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");


            
            #line 87 "..\..\Views\HttpReports\Monitor.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <button style=\"margin:4px\" type=\"button" +
"\" onclick=\"delJob(\'");


            
            #line 89 "..\..\Views\HttpReports\Monitor.cshtml"
                                                                                             Write(item.Id);

            
            #line default
            #line hidden
WriteLiteral("\')\" class=\"btn btn-danger btn-xs\"><span class=\"glyphicon glyphicon-remove-sign\"><" +
"/span> ");


            
            #line 89 "..\..\Views\HttpReports\Monitor.cshtml"
                                                                                                                                                                                             Write(lang.Monitor_Delete);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\r\n                                    </td>\r\n                         " +
"       </tr>\r\n");


            
            #line 93 "..\..\Views\HttpReports\Monitor.cshtml"

                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </tbody>\r\n                    </table>\r\n\r\n             " +
"   </div>\r\n            </div>\r\n\r\n        </div>\r\n\r\n    </div>\r\n\r\n</div>\r\n\r\n<scri" +
"pt src=\"/HttpReportsStaticFiles/Content/page/monitor.js?ver=1.0.5\"></script>\r\n");


        }
    }
}
#pragma warning restore 1591
