#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttpReports.Dashboard.Views
{
    using System;
    
    #line 3 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class RequestInfoDetail : HttpReports.Dashboard.Views.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




            
            #line 4 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
  
    ViewData["Title"] = "RequestInfoDetail";

    var RequestInfo = ViewData["Info"] as HttpReports.IRequestInfo;

    var RequestDetail = ViewData["Detail"] as HttpReports.IRequestDetail;

    var lang = ViewData["Language"] as HttpReports.Dashboard.Services.Localize;

    Layout = new HttpReports.Dashboard.Views.HttpReportsTemplate { Context = Context, ViewData = ViewData };



            
            #line default
            #line hidden
WriteLiteral(@"
<style type=""text/css"">

    .table td, th {
        text-align: center;
        line-height: 24px !important;
        font-size: 12px;
    }
</style>

<div class=""panel panel-default"">

    <div class=""panel-body"" style=""padding-left:30px;padding-right:30px;padding-top:30px;padding-bottom:30px"">

        <div class=""row col-sm-9"">

            <div class=""panel panel-default"">

                <div class=""panel-body"" style=""padding-bottom:20px"">

");


            
            #line 36 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                     if (RequestInfo == null || RequestDetail == null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <h3 class=\"request_detail_notfound\">");


            
            #line 38 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                                       Write(lang.Request_NotFound);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n");


            
            #line 39 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <h3 class=\"request_detail_title\" style=\"padding-left:6px;" +
"margin-bottom:30px\"><i class=\"fa fa-star-half-o\" style=\"margin-right:10px\"></i> " +
" 请求基础信息</h3>\r\n");


            
            #line 43 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"


            
            #line default
            #line hidden
WriteLiteral(@"                        <table class=""table table-striped table-bordered"">
                            <thead>
                                <tr>
                                    <th width=""160"">Key</th>
                                    <th>Value</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>RequestId</td>
                                    <td style=""text-align:left;font-size:12px;padding-left:8px"">");


            
            #line 54 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                                                                           Write(RequestInfo.Id);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n                                <tr" +
">\r\n                                    <td>");


            
            #line 57 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                   Write(lang.Index_ServiceNode);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td style=\"text-align:left;font-size:1" +
"2px;padding-left:8px\">");


            
            #line 58 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                                                                           Write(RequestInfo.Node);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n                                <tr" +
">\r\n                                    <td>");


            
            #line 61 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                   Write(lang.Request_Route);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td style=\"text-align:left;font-size:1" +
"2px;padding-left:8px\">");


            
            #line 62 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                                                                           Write(RequestInfo.Route);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n\r\n                                <" +
"tr>\r\n                                    <td>");


            
            #line 66 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                   Write(lang.Request_Url);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td style=\"text-align:left;font-size:1" +
"2px;padding-left:8px\">");


            
            #line 67 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                                                                           Write(RequestInfo.Url);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n\r\n                                <" +
"tr>\r\n                                    <td>");


            
            #line 71 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                   Write(lang.Request_Type);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td style=\"text-align:left;font-size:1" +
"2px;padding-left:8px\">");


            
            #line 72 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                                                                           Write(RequestInfo.Method);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n\r\n                                <" +
"tr>\r\n                                    <td>");


            
            #line 76 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                   Write(lang.Request_Time);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td style=\"text-align:left;font-size:1" +
"2px;padding-left:8px\">");


            
            #line 77 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                                                                           Write(RequestInfo.Milliseconds);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n\r\n                                <" +
"tr>\r\n                                    <td>");


            
            #line 81 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                   Write(lang.Request_StatusCode);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td style=\"text-align:left;font-size:1" +
"2px;padding-left:6px\">");


            
            #line 82 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                                                                           Write(RequestInfo.StatusCode);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n\r\n                                <" +
"tr>\r\n                                    <td>");


            
            #line 86 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                   Write(lang.Request_RemoteIP);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td style=\"text-align:left;font-size:1" +
"2px;padding-left:6px\">");


            
            #line 87 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                                                                           Write(RequestInfo.IP);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n\r\n                                <" +
"tr>\r\n                                    <td>");


            
            #line 91 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                   Write(lang.Request_CreateTime);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td style=\"text-align:left;font-size:1" +
"2px;padding-left:6px\">");


            
            #line 92 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                                                                           Write(RequestInfo.CreateTime.ToString("yyyy-MM-dd HH:mm:ss fff"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n\r\n\r\n                            </t" +
"body>\r\n                        </table>\r\n");


            
            #line 98 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                        <h3 class=\"request_detail_title\" style=\"padding-left:6px;" +
" margin-top:50px;margin-bottom:30px\"><i class=\"fa fa-space-shuttle\" style=\"margi" +
"n-right:10px\"></i>  请求详细信息</h3>\r\n");


            
            #line 100 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"


            
            #line default
            #line hidden
WriteLiteral(@"                        <table class=""table table-striped table-bordered"">
                            <thead>
                                <tr>
                                    <th width=""160"">Key</th>
                                    <th>Value</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>QueryString</td>
                                    <td style=""text-align:left;font-size:12px"">");


            
            #line 111 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                                                          Write(RequestDetail.QueryString);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n\r\n                                <" +
"tr>\r\n                                    <td>Header</td>\r\n                      " +
"              <td style=\"text-align:left;font-size:12px\">");


            
            #line 116 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                                                          Write(RequestDetail.Header);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n\r\n                                <" +
"tr>\r\n                                    <td>Cookie</td>\r\n                      " +
"              <td style=\"text-align:left;font-size:12px\">");


            
            #line 121 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                                                          Write(RequestDetail.Cookie);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n\r\n                                <" +
"tr>\r\n                                    <td>RequestBody</td>\r\n                 " +
"                   <td style=\"text-align:left;font-size:12px\">");


            
            #line 126 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                                                          Write(RequestDetail.RequestBody);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n\r\n\r\n                               " +
" <tr>\r\n                                    <td>ResponseBody</td>\r\n              " +
"                      <td style=\"text-align:left;font-size:12px\">");


            
            #line 132 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                                                          Write(RequestDetail.ResponseBody);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n\r\n                                <" +
"tr>\r\n                                    <td>Error</td>\r\n                       " +
"             <td style=\"text-align:left;font-size:12px\">");


            
            #line 137 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                                                          Write(RequestDetail.ErrorMessage);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n\r\n                                <" +
"tr>\r\n                                    <td>ErrorStack</td>\r\n                  " +
"                  <td style=\"text-align:left;font-size:12px\">");


            
            #line 142 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"
                                                                          Write(RequestDetail.ErrorStack);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n\r\n\r\n                            </t" +
"body>\r\n                        </table>\r\n");


            
            #line 148 "..\..\Views\HttpReports\RequestInfoDetail.cshtml"

                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                </div>\r\n\r\n            </div>\r\n\r\n        </div>\r\n\r\n\r\n    </div" +
">\r\n\r\n</div>\r\n\r\n\r\n<script src=\"/HttpReportsStaticFiles/Content/page/requestinfo_d" +
"etail.js?ver=1.0.5\"></script>\r\n");


        }
    }
}
#pragma warning restore 1591
